kind: pipeline
type: docker
name: default

steps:
- name: Build
  image: rust:1.46.0-alpine
  commands:
  - apk update && apk upgrade
  - apk add pacman pacman-dev gcc libc-dev
  - cargo build --all

- name: Test
  image: rust:1.46.0-alpine
  commands:
  - apk update && apk upgrade
  - apk add pacman pacman-dev gcc libc-dev
  - cargo test --all
