kind: pipeline
type: docker
name: default

steps:
- name: test
  image: rust:1.46.0-alpine
  commands:
  - apk update
  - apk upgrade
  - apk add pacman pacman-dev gcc musl
  - cargo build --all
  - cargo test --all
