[package]
name = "alpm_test"
version = "0.1.0"
authors = ["jojii <jojii@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alpm = "0.10.1"
aur-client = "0.1.3"
pkginfo = "0.1.2"